
package cn.rootyu.ims.webService.client.nocm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NocmService", targetNamespace = "http://service.webService.ims.dhc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NocmService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.dhc.ims.webservice.service.NocmTaskWce
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inspect", targetNamespace = "http://service.webService.ims.dhc.com/", className = "com.dhc.ims.webservice.service.Inspect")
    @ResponseWrapper(localName = "inspectResponse", targetNamespace = "http://service.webService.ims.dhc.com/", className = "com.dhc.ims.webservice.service.InspectResponse")
    public NocmTaskWce inspect(
            @WebParam(name = "arg0", targetNamespace = "")
                    NocmTaskWce arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<NocmTaskResult> arg1);

}
