
package cn.rootyu.ims.webService.client.nocm;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NocmService", targetNamespace = "http://service.webService.ims.dhc.com/", wsdlLocation = "http://172.16.9.113:8080/QMIS/webService/NocmService?wsdl")
public class NocmService_Service
    extends Service
{

    private final static URL NOCMSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOCMSERVICE_EXCEPTION;
    private final static QName NOCMSERVICE_QNAME = new QName("http://service.webService.ims.dhc.com/", "NocmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.9.113:8080/QMIS/webService/NocmService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOCMSERVICE_WSDL_LOCATION = url;
        NOCMSERVICE_EXCEPTION = e;
    }

    public NocmService_Service() {
        super(__getWsdlLocation(), NOCMSERVICE_QNAME);
    }

    public NocmService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOCMSERVICE_QNAME, features);
    }

    public NocmService_Service(URL wsdlLocation) {
        super(wsdlLocation, NOCMSERVICE_QNAME);
    }

    public NocmService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOCMSERVICE_QNAME, features);
    }

    public NocmService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NocmService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NocmService
     */
    @WebEndpoint(name = "NocmServiceImplPort")
    public NocmService getNocmServiceImplPort() {
        return super.getPort(new QName("http://service.webService.ims.dhc.com/", "NocmServiceImplPort"), NocmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NocmService
     */
    @WebEndpoint(name = "NocmServiceImplPort")
    public NocmService getNocmServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webService.ims.dhc.com/", "NocmServiceImplPort"), NocmService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOCMSERVICE_EXCEPTION!= null) {
            throw NOCMSERVICE_EXCEPTION;
        }
        return NOCMSERVICE_WSDL_LOCATION;
    }

}
