
package cn.rootyu.ims.webService.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2017-02-15T10:24:38.454+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class MessageService_MessageServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.webService.ims.rootyu.cn/", "MessageService");

    private MessageService_MessageServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MessageService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessageService_Service ss = new MessageService_Service(wsdlURL, SERVICE_NAME);
        MessageService port = ss.getMessageServiceImplPort();  
        
        {
        System.out.println("Invoking getMessage...");
        String _getMessage_text = "TEST";
        String _getMessage__return = port.getMessage(_getMessage_text);
        System.out.println("getMessage.result=" + _getMessage__return);


        }

        System.exit(0);
    }

}
