package cn.rootyu.ims.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2017-02-15T10:24:38.510+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "MessageService", 
                  wsdlLocation = "http://localhost:8080/QMIS/webService/MessageService?wsdl",
                  targetNamespace = "http://service.webService.ims.dhc.com/")
public class MessageService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webService.ims.dhc.com/", "MessageService");
    public final static QName MessageServiceImplPort = new QName("http://service.webService.ims.dhc.com/", "MessageServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/QMIS/webService/MessageService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessageService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/QMIS/webService/MessageService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MessageService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessageService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServiceImplPort")
    public MessageService getMessageServiceImplPort() {
        return super.getPort(MessageServiceImplPort, MessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageService
     */
    @WebEndpoint(name = "MessageServiceImplPort")
    public MessageService getMessageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MessageServiceImplPort, MessageService.class, features);
    }

}
